### ISSUE TITLE
It's not clear from the docs how to set up schedule of a task.

### ISSUE THREAD

**Issue by yarikos** [elasticio/api-docs#22]

**Comment by khanzadyan** [comment]
The issue is outdated. It is possible to set schedule of the flow using `attributes.cron`. In addition this is not the purpose of API documentation to explain this. elastic.io docs already explain this: https://docs.elastic.io/guides/managing-flows.html#scheduling

**Comment by yarikos** [comment]
Thank you @khanzadyan
