### ISSUE TITLE
_tenants.md should also include rebranded information

### ISSUE THREAD

**Issue by vdidushko** [elasticio/api-docs#332]
"header_logo_url":"//cdn.elastic.io/logo-mini.png",
      "loading_logo_url":"//cdn.elastic.io/logo-mini.png",
      "email_logo_url":"//cdn.elastic.io/logo-mini.png",
      "favicon_url":"//cdn.elastic.io/logo-mini.png",
      "terms_of_usage_url":"https://www.elastic.io/tou/",
      "privacy_policy_url":"https://www.elastic.io/privacy-policy/",
      "imprint_url":"https://www.elastic.io/legal-disclosure/",
       "documentation":"https://docs.elastic.io/"

**Comment by pnedelko** [comment]
Solved in https://github.com/elasticio/api-docs/pull/378.

**Comment by khanzadyan** [comment]
Closing the issue as done.
