### ISSUE TITLE
Get rid of elasticio mentions

### ISSUE THREAD

**Issue by pnedelko** [elasticio/api-docs#379]
There are still some elasticio mentions that we need to get rid of in order docs to be better white labeled.

<img width="1312" alt="Monosnap 2019-10-23 16-17-42" src="https://user-images.githubusercontent.com/2523461/67402277-a69f0780-f5b0-11e9-8bc7-6649c44d7eaa.png">

**Comment by khanzadyan** [comment]
Removed the mentions.
